### ISSUE TITLE
esrally start successfully but not listen at all

### ISSUE THREAD

**Issue by UchihaYuki** [elastic/rally#1480] opened 2022-05-06 13:47 UTC
**Rally version** (get with `esrally --version`): esrally 2.4.0

**Invoked command**:
```shell
export PUBLIC_IP=127.0.0.1 # I tried both my real public ip and 127.0.0.1
export INSTALLATION_ID=$(esrally install --quiet --distribution-version=8.1.2 --node-name="rally-node-0" --network-host="${PUBLIC_IP}" --http-port=39200 --master-nodes="rally-node-0" --seed-hosts="${PUBLIC_IP}:39300" | jq --raw-output '.["installation-id"]') 
export RACE_ID=$(uuid)
esrally start --installation-id="${INSTALLATION_ID}" --race-id="${RACE_ID}"
netstat -tuplen
```

**Configuration file (located in `~/.rally/rally.ini`))**: 
```
[meta]
config.version = 17

[system]
env.name = local

[node]
root.dir = /root/.rally/benchmarks
src.root.dir = /root/.rally/benchmarks/src

[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /root/.rally/benchmarks/data

[reporting]
datastore.type = in-memory
datastore.host =
datastore.port =
datastore.secure = False
datastore.user =
datastore.password =


[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = false

[distributions]
release.cache = true
```

**JVM version**:
```
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```

**OS version**:
```
Linux esrally-1-3 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
It should listen on port 39200 and 39300, but it doesn't. I have run `install start stop` circle several times on the same machine, I don't know if this matters.

**Steps to reproduce**: please see Invoked command

**Provide logs (if relevant)**:
```
[INFO] SUCCESS (took 2 seconds)
```

**Comment by DJRickyB** [comment] 2022-05-06 13:55
I cannot reproduce this locally, though I am on macos. 

Note that if Elasticsearch fails after `esrally start` completes, it will not necessarily show up. After you invoke `esrally start` do you see the process running in the output of `ps -ef|grep Elasticsearch`? 

If it fails you can see the logs in `$HOME/.rally/benchmarks/races/$INSTALLATION_ID/rally-node-0/logs` to determine what's happening

**Comment by UchihaYuki** [comment] 2022-05-06 14:26
Yes, it's running.
```shell
~$ ps -ef|grep Elasticsearch
elastic+   31549   31540  0 14:21 pts/0    00:00:00 grep --color=auto Elasticsearch
~$ netstat -tuplen
(No info could be read for "-p": geteuid()=1000 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      101        18007      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          21576      -
tcp6       0      0 :::22                   :::*                    LISTEN      0          21578      -
udp        0      0 127.0.0.53:53           0.0.0.0:*                           101        18006      -
```
There is no folder called benchmarks:
```shell
ls -l .rally
total 12
-rw-r--r-- 1 elasticsearch users 1382 May  6 11:10 logging.json
drwxr-xr-x 2 elasticsearch users 4096 May  6 11:10 logs
-rw-r--r-- 1 elasticsearch users  713 May  6 11:10 rally.ini
```

**Comment by DJRickyB** [comment] 2022-05-06 17:07
This output does not contain the Elasticsearch `java` process. it is not running
```
~$ ps -ef|grep Elasticsearch
elastic+   31549   31540  0 14:21 pts/0    00:00:00 grep --color=auto Elasticsearch
```

My mistake regarding the benchmarks directory, your `rally.ini` shows this will be in `/root/.rally/`. 

As we have not been able to reproduce this now on MacOS or Linux I will close this issue. If you need further assistance please post in the forums at https://discuss.elastic.co, if we determine there is a confirmed bug we can open a new issue here.

**Closed** 2022-05-06 17:07 UTC
