### ISSUE TITLE
Esrally doesn't report results to configured Elasticsearch when run from ansible

### ISSUE THREAD

**Issue by akshay21** [elastic/rally#626] opened 2019-01-08 15:54 UTC
**Rally version** (get with `esrally --version`):
esrally 1.0.2

**Invoked command**:
esrally --track=eventdata --target-hosts=XX.XX.XX.XX --pipeline=benchmark-only

**Configuration file (located in `~/.rally/rally.ini`))**:
[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /home/ubuntu/.rally/benchmarks/data

[reporting]
datastore.type = elasticsearch
datastore.host = YY.YY.YY.YY
datastore.port = 9200
datastore.secure = False
datastore.user =
datastore.password =

[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = False

[distributions]
release.cache = true

**JVM version**:
10.0.2

**OS version**:
Ubuntu 18.04

**Description of the problem including expected versus actual behavior**:
When I run the command: `esrally --track=eventdata --target-hosts=XX.XX.XX.XX --pipeline=benchmark-only`, where XX is the ip address of my target Elasticsearch, from the terminal of the test node on which esrally is installed the esrally runs the test on target Elasticsearch and store results in the another Elasticsearch configured in rally.ini . 

But, when I run the same command from the ansible playbook the target Elasticsearch is tested but the results are not reported to the Elasticsearch storing the results of the tests.

**Steps to reproduce**:
 1. Run the rally tests manually and see that results are reported to the Elasticsearch
 2. Run the rally test from an ansible playbook.
 3. Check if the results are reported to the Elasticsearch.

**Comment by dliappis** [comment] 2019-01-08 18:06
Please note that GitHub issues are reserved for confirmed bugs and feature requests.
For items like this it's best to open a topic in https://discuss.elastic.co/c/elasticsearch/rally first.

Regarding your issue, I am unable to reproduce this.

With the metric store configured in `~/.rally/rally.ini`:

<details>
<summary>rally.ini</summary>

```
[meta]
config.version = 17

[system]
env.name = local

[node]
root.dir = /Users/dl/.rally/benchmarks
src.root.dir = /Users/dl/.rally/benchmarks/src

[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /Users/dl/.rally/benchmarks/data

[reporting]
datastore.type = elasticsearch
datastore.host = 127.0.0.1
datastore.port = 19202
datastore.secure = False
datastore.user = XXX
datastore.password = YYYY

[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = False

[distributions]
release.cache = true
```
</details>


I can run both:

```
esrally --track=geopoint --target-hosts=127.0.0.1:19201 --pipeline=benchmark-only
```

and then I can also execute Rally via a shell wrapper script and Ansible:

```
cat foo.sh
#!/bin/bash
source .venv/bin/activate
esrally --track=geopoint --target-hosts=127.0.0.1:19201 --pipeline=benchmark-only
```

```
ansible -i localhost, -c local -m shell -a './foo.sh' all
```

While Ansible runs, it's normal that there's no TTY output by Rally as checks whether it's running in a real terminal, however, logs flow normally in `~/.rally/rally.log` and metrics get populated correctly to my local metric store which I can inspect e.g. using:

```
$ curl localhost:19202/rally-metrics-2019-01/_search?pretty\&size=1
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1280,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "rally-metrics-2019-01",
        "_type" : "metrics",
        "_id" : "lbebLmgBaWxo5rpyhRO6",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : 1546970167333,
          "relative-time" : 1560666,
          "trial-id" : "9369b6cd-e774-4e36-aa32-06712fe894e8",
          "trial-timestamp" : "20190108T175536Z",
          "environment" : "local",
          "track" : "geopoint",
          "lap" : 1,
          "challenge" : "append-no-conflicts",
          "car" : "external",
          "name" : "latency",
          "value" : 1559.082619001856,
          "unit" : "ms",
          "sample-type" : "normal",
          "meta" : {
            "attribute_ml.machine_memory" : "34359738368",
            "attribute_xpack.installed" : "true",
            "attribute_ml.max_open_jobs" : "20",
            "source_revision" : "67f97e3",
            "distribution_version" : "7.0.0-SNAPSHOT",
            "success" : true
          },
          "task" : "delete-index",
          "operation" : "delete-index",
          "operation-type" : "DeleteIndex"
        }
      }
    ]
  }
}
```

Have you double checked that results aren't really present in your defined metric store?

**Comment by akshay21** [comment] 2019-01-08 21:38
Hi @dliappis ,

Thank you for getting back to me so quickly!
I double checked but still metrics are not being stored in the Elasticsearch.
 Below is the block from my ansible playbook.
```
- name: Run esrally test
  shell: |
    source /home/{{ ansible_user }}/bin/activate
    esrally --track=eventdata --target-hosts={{ elastic_server }} --pipeline=benchmark-only 
  args:
    executable: /bin/bash
  register: esout

- debug: msg="{{ esout.stdout }}"

- debug: msg="{{ esout.stderr }}"
```

I don't know what difference does having a local data store make?

**Comment by dliappis** [comment] 2019-01-09 16:51
I just used your playbook and against a fresh Elasticsearch 6.5.3 (started with Docker) and I can confirm that the metrics store gets populated without issues:

```
$ docker run -d --rm -p 19202:9200 docker.elastic.co/elasticsearch/elasticsearch:6.5.3
8c2617c92618716e5aae7f59f0d53aad1393fba32f981cf94f97d157606243e6
Dimitrioss-MacBook-Pro:tmp dl$ curl localhost:19202?pretty
{
  "name" : "RtbRdN2",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "C2F25tXLS4iIpEmEhLprTg",
  "version" : {
    "number" : "6.5.3",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "159a78a",
    "build_date" : "2018-12-06T20:11:28.826501Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

$ curl localhost:19202/_cat/indices

$ cat playbook.yml
- name: test
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: Run esrally test
      shell: |
        source /home/{{ ansible_user }}/bin/activate
        esrally --configuration-name=metricstore --track=geopoint --target-hosts=127.0.0.1:19201 --pipeline=benchmark-only
      args:
        executable: /bin/bash
      register: esout

    - debug: msg="{{ esout.stdout }}"

    - debug: msg="{{ esout.stderr }}"
Dimitrioss-MacBook-Pro:tmp dl$ ansible-playbook -i localhost, ./playbook.yml

PLAY [test] ***************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Run esrally test] ***************************************************************************************************************************************************************************************************************************
```

(my `~/.rally/rally-metricstore.ini` is defining 127.0.0.1:19202 for the metric store)

and during the playbook execution:

```
$ curl localhost:19202/_cat/indices
yellow open rally-metrics-2019-01 WJ7cknwdRD2mFqRL1b1qLQ 1 1 1282 0 235kb 235kb
```

and data keeps growing.

As we reserve GitHub for _verified_ bug reports, I am going to close this, but please feel free to move the discussion to a new topic in https://discuss.elastic.co/c/elasticsearch/rally where we can investigate this further (I recommend to take a look in `~/.rally/logs/rally.log` first).

**Closed by dliappis** 2019-01-09 16:51 UTC
