### ISSUE TITLE
Error when running in benchmark-only mode

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/rally#110] opened 2016-06-30 20:20 UTC
I get the following error. Didn't really investigate, but looks like we need a check to see if the report returns a valid value.  

Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/esrally/rally.py", line 276, in main
    success = dispatch_sub_command(cfg, sub_command)
  File "/usr/local/lib/python3.4/site-packages/esrally/rally.py", line 228, in dispatch_sub_command
    return race_control.start(sub_command)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 317, in start
    raise e
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 297, in start
    pipeline()
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 94, in __call__
    step()
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 25, in __call__
    self.command(self.ctx)
  File "/usr/local/lib/python3.4/site-packages/esrally/racecontrol.py", line 271, in <lambda>
    PipelineStep("report", ctx, lambda ctx: ctx.reporter.report(ctx.track)),
  File "/usr/local/lib/python3.4/site-packages/esrally/reporter.py", line 161, in report
    metrics_table += self.report_gc_times(stats)
  File "/usr/local/lib/python3.4/site-packages/esrally/reporter.py", line 232, in report_gc_times
    ["Total Young Gen GC [s]", convert.ms_to_seconds(stats.young_gc_time)],
  File "/usr/local/lib/python3.4/site-packages/esrally/utils/convert.py", line 18, in ms_to_seconds
    return ms / 1000.0
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by danielmitterdorfer** [comment] 2016-07-01 05:00
Can you please provide a bit more information so I can reproduce it?

* The command line parameter you provided to Rally
* Elasticsearch version of the cluster you've benchmarked
* If possible also the log file (this is usually located in `~/.rally/benchmarks/races/$UTC_TIMESTAMP_OF_INVOCATION/local/`)

Then this should be fairly easy to fix.

**Comment by danielmitterdorfer** [comment] 2016-07-01 05:19
If you don't mind running Rally from master (see [docs](https://esrally.readthedocs.io/en/latest/developing.html#installation-instructions-for-development)) the fix will also be pretty quickly in.

**Comment by danielmitterdorfer** [comment] 2016-07-07 03:32
@eugenemiretsky Were you able to reproduce it?

**Comment by danielmitterdorfer** [comment] 2016-07-11 05:59
I tried to reproduce it with the latest master, latest 2.x and 1.7.5 and could not reproduce it locally. Hence, I am closing the ticket but please feel free to reopen if you can reproduce it.

**Comment by eugenemiretsky** [comment] 2016-07-14 22:02
Sorry for late response: 
Cmd: esrally --pipeline=benchmark-only --target-hosts=xxxx --user-tag intention:test
ES version: 2.1.1
Log: https://drive.google.com/file/d/0B5zMYwUERjCOTHBFX0ZRcU5NbjA/view?usp=sharing

**Comment by danielmitterdorfer** [comment] 2016-07-15 05:51
I can see from the logs that you've used an Elasticsearch metrics store. I can reproduce the problem now locally. Thanks for the logs.

**Comment by danielmitterdorfer** [comment] 2016-07-15 05:53
For the record. Reproduction scenario (based on latest master):

* Extract Elasticsearch 2.1.1. and start (benchmark cluster)
* Setup a fresh Elasticsearch metrics store and configure Rally to use it

Run ``esrally --pipeline=benchmark-only --track=tiny``. 

Produces:

```
dm@io:Projects/rally ‹master›$ esrally --pipeline=benchmark-only --track=tiny

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/


Writing additional logs to /Users/dm/.rally/benchmarks/races/2016-07-15-05-50-12/local/logs/rally_out.log


************************************************************************
************** WARNING: A dark dungeon lies ahead of you  **************
************************************************************************

Rally dos not have control over the configuration of the benchmarked
Elasticsearch cluster.

Be aware that results may be misleading due to problems with the setup.
Rally is also not able to gather lots of metrics at all (like CPU usage
of the benchmarked cluster) or may even produce misleading metrics (like
the index size).

************************************************************************
****** Use this pipeline only if you are aware of the tradeoffs.  ******
*************************** Watch your step! ***************************
************************************************************************

Racing on track [tiny] and challenge [append-no-conflicts]
  Benchmarking indexing at 22355.5 docs/s                            [100% done]
  Benchmarking stats (warmup iteration 100/100)                      [100% done]
  Benchmarking stats (iteration 100/100)                             [100% done]
  Benchmarking search (warmup iteration 1000/1000)                   [100% done]
  Benchmarking search (iteration 1000/1000)                          [100% done]
------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

FATAL: Cannot race

Reason: 'NoneType' object has no attribute 'items'

Please check the log file [/Users/dm/.rally/benchmarks/races/2016-07-15-05-50-12/local/logs/rally_out.log] for further details first.

If you need further help, please check Rally's docs at https://esrally.readthedocs.io or ask a question in the forum at https://discuss.elastic.co/c/elasticsearch.

If you think this is a bug, please file a report at https://github.com/elastic/rally/issues and include the log file for this race (/Users/dm/.rally/benchmarks/races/2016-07-15-05-50-12/local/logs/rally_out.log).
```

**Comment by danielmitterdorfer** [comment] 2016-07-15 06:21
Fixed with the latest master build. Thanks for following up Eugene.

**Closed** 2016-07-15 06:21 UTC
Labels: bug
