### ISSUE TITLE
Esrally not able to deploy in kubernetes

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [elastic/rally#1295] opened 2021-06-29 10:56 UTC
Hi All,

I tried deploying es rally in k8s environment and I got the below messages in logs,

```
[WARNING] No Internet connection detected. Automatic download of track data sets etc. is disabled.
[INFO] You did not provide an explicit timeout in the client options. Assuming default of 10 seconds.
[ERROR] Cannot race. Error in race control (Expected a git repository at [/rally/.rally/benchmarks/tracks/default] but the directory does not exist.)
```

Note:- I dont have internet access to this cluster.

To resolve the above issue I tried the below things,

tried mounting the local path to pod using hostpath,
 ```
       volumeMounts:
        - name: esrally-data
          mountPath: /rally/.rally
        - name: trackparams-cfg-vol
          mountPath: /rally/params.json
          subPath: params.json
        - name: cert-ca
          mountPath: /data/certificates/
        - name: tracks
          mountPath: /rally/.rally/benchmarks
      restartPolicy: OnFailure
      volumes:
      - name: esrally-data
        persistentVolumeClaim:
          claimName: esrally-claim
      - name: trackparams-cfg-vol
        configMap:
          name: esrally-trackparams-cfg
      - name: cert-ca
        secret:
          secretName: elasticsearch-certs
      - name: tracks
        hostPath:
          path: /root/.rally/benchmarks
```
and I got this message in pod logs,

[root@k8master1 ~]# kubectl logs esrally-ct7bv -n es -f
```

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] You did not provide an explicit timeout in the client options. Assuming default of 10 seconds.
[ERROR] Cannot race. Error in race control ([/rally/.rally/benchmarks/tracks/default] must be a git repository.

Please run:
git -C /rally/.rally/benchmarks/tracks/default init)

Getting further help:
*********************
* Check the log files in /rally/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/2.2.0/.
* Ask a question on the forum at https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally.
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /rally/.rally/logs.
```
please correct me if I am doing anything wrong.

Thanks,
Ganeshbabu R

**Comment by dliappis** [comment] 2021-06-30 09:46
Thank you very much for your interest in Elasticsearch.

This appears to be a user question and seems to be a duplicate of the question you've opened in the discuss forum: https://discuss.elastic.co/t/esrally-error-in-k8s-cluster-and-not-able-to-deploy/277143/7. We use GitHub for _verified_ bug reports, feature requests, and pull requests.

Please be patient in waiting for responses to your question and refrain from opening additional issues for the same question. Being a community forum, it may take time for someone to reply to your question. For more information please refer to the [Community Code of Conduct](https://www.elastic.co/community/codeofconduct) specifically the section "Be patient".

If you are in need of a service with an SLA that covers response times for questions then you may want to consider talking to us about a [subscription](https://www.elastic.co/subscriptions).

As such, I hope you don't mind that I close this.

**Closed by dliappis** 2021-06-30 09:46 UTC
