### ISSUE TITLE
Many indicators are output empty

### ISSUE THREAD

**Issue by hexian55** [elastic/rally#237] opened 2017-02-22 02:27 UTC
**Rally version** (get with `esrally --version`):
esrally 0.4.8

**Invoked command**:
esrally --distribution-version=5.0.1

**Configuration file (located in `~/.rally/rally.ini`))**:
[meta]
config.version = 6

[system]
root.dir = /home/work/.rally/benchmarks
log.root.dir = logs
env.name = esrally_test

[provisioning]
local.install.dir = install

[runtime]
java8.home = /home/work/app/jdk1.8.0_111

[benchmarks]
local.dataset.cache = ${system:root.dir}/data

[reporting]
datastore.type = elasticsearch
datastore.host = localhost
datastore.port = 9200
datastore.secure = False
datastore.user =
datastore.password =

[tracks]
default.url = https://github.com/elastic/rally-tracks

[defaults]
preserve_benchmark_candidate = True

**JVM version**:

**OS version**:
centos 7.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

output:
------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
/ __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

|   Lap |                          Metric |            Operation |     Value |   Unit |
|------:|--------------------------------:|---------------------:|----------:|-------:|
|   All |                   Indexing time |                      |   33.2486 |    min |
|   All |                      Merge time |                      |   7.03988 |    min |
|   All |                    Refresh time |                      |   1.28523 |    min |
|   All |                      Flush time |                      | 0.0920167 |    min |
|   All |             Merge throttle time |                      |  0.526933 |    min |
|   All |                Median CPU usage |                      |   468.176 |      % |
|   All |              Total Young Gen GC |                      |    15.326 |      s |
|   All |                Total Old Gen GC |                      |     1.184 |      s |
|   All |        Heap used for doc values |                      | 0.0941429 |     MB |
|   All |             Heap used for terms |                      |   13.1741 |     MB |
|   All |             Heap used for norms |                      | 0.0684814 |     MB |
|   All |            Heap used for points |                      |  0.579043 |     MB |
|   All |     Heap used for stored fields |                      |  0.624725 |     MB |
|   All |                   Segment count |                      |        89 |        |
|   All |                  Min Throughput |         index-append |           |        |
|   All |               Median Throughput |         index-append |           |        |
|   All |                  Max Throughput |         index-append |           |        |
|   All |                  Min Throughput |          force-merge |           |        |
|   All |               Median Throughput |          force-merge |           |        |
|   All |                  Max Throughput |          force-merge |           |        |
|   All |                  Min Throughput |          index-stats |           |        |
|   All |               Median Throughput |          index-stats |           |        |
|   All |                  Max Throughput |          index-stats |           |        |
|   All |       50.0th percentile latency |          index-stats |    1.5946 |     ms |
|   All |       90.0th percentile latency |          index-stats |   1.67269 |     ms |
|   All |       99.0th percentile latency |          index-stats |    2.5369 |     ms |
|   All |      100.0th percentile latency |          index-stats |   29.9786 |     ms |
|   All |  50.0th percentile service time |          index-stats |   1.53625 |     ms |
|   All |  90.0th percentile service time |          index-stats |   1.60196 |     ms |
|   All |  99.0th percentile service time |          index-stats |   1.92153 |     ms |
|   All | 100.0th percentile service time |          index-stats |   11.7068 |     ms |
|   All |                  Min Throughput |           node-stats |           |        |
|   All |               Median Throughput |           node-stats |           |        |
|   All |                  Max Throughput |           node-stats |           |        |
|   All |       50.0th percentile latency |           node-stats |   1.62292 |     ms |
|   All |       90.0th percentile latency |           node-stats |   1.80209 |     ms |
|   All |       99.0th percentile latency |           node-stats |   4.67785 |     ms |
|   All |      100.0th percentile latency |           node-stats |   13.2262 |     ms |
|   All |  50.0th percentile service time |           node-stats |   1.55853 |     ms |
|   All |  90.0th percentile service time |           node-stats |   1.74619 |     ms |
|   All |  99.0th percentile service time |           node-stats |   2.48444 |     ms |
|   All | 100.0th percentile service time |           node-stats |    13.168 |     ms |
|   All |                  Min Throughput |              default |           |  ops/s |
|   All |               Median Throughput |              default |           |  ops/s |
|   All |                  Max Throughput |              default |           |  ops/s |
|   All |                  Min Throughput |                 term |           |        |
|   All |               Median Throughput |                 term |           |        |
|   All |                  Max Throughput |                 term |           |        |
|   All |                  Min Throughput |               phrase |   200.104 |        |
|   All |               Median Throughput |               phrase |   200.123 |        |
|   All |                  Max Throughput |               phrase |   200.143 |        |
|   All |                  Min Throughput | country_agg_uncached |   6.16675 |        |
|   All |               Median Throughput | country_agg_uncached |   6.26778 |        |
|   All |                  Max Throughput | country_agg_uncached |   6.28171 |        |
|   All |                  Min Throughput |   country_agg_cached |    100.07 |        |
|   All |               Median Throughput |   country_agg_cached |   100.126 |        |
|   All |                  Max Throughput |   country_agg_cached |   100.182 |        |
|   All |                  Min Throughput |               scroll |   56.8402 |        |
|   All |               Median Throughput |               scroll |   56.8896 |        |
|   All |                  Max Throughput |               scroll |   57.0091 |        |
|   All |                  Min Throughput |           expression |   3.82189 |        |
|   All |               Median Throughput |           expression |   3.83776 |        |
|   All |                  Max Throughput |           expression |   3.86058 |        |
|   All |                  Min Throughput |      painless_static |   2.50521 |        |
|   All |               Median Throughput |      painless_static |   2.51079 |        |
|   All |                  Max Throughput |      painless_static |   2.51662 |        |
|   All |                  Min Throughput |     painless_dynamic |   2.23677 |        |
|   All |               Median Throughput |     painless_dynamic |   2.24671 |        |
|   All |                  Max Throughput |     painless_dynamic |   2.26263 |        |

Many indicators are output empty,why?

**Comment by danielmitterdorfer** [comment] 2017-02-22 12:47
Thanks for the report @hexian55! Your configuration and the invocation look fine to me. 

Empty throughput results are caused by to few samples (which is addressed by caa3e60d887133909905c9dfe048d5f2c33adf38 and included in the next release 0.5.0) or when the cluster does not return proper results but instead returns errors (e.g. HTTP 404) which we will improve with #234.

I am almost certain that this error should be gone with 0.5.0. Could you please retry with 0.5.0 once it is out (*probably* tomorrow)? I'll add a comment here in the ticket once the release is out.

**Comment by hexian55** [comment] 2017-02-23 02:32
Thank you for your answer ,
But I now need the results of these stress tests to make an assessment of my future cluster.
you can give me a test result based on es5.0.1?

**Comment by danielmitterdorfer** [comment] 2017-02-23 08:08
@hexian55 It would not help you much if I provide results base on our hardware but Rally 0.5.0 is now out and you can upgrade with `pip3 install --upgrade esrally`. Btw, are you aware that we publish our benchmark results at https://elasticsearch-benchmarks.elastic.co/?

**Comment by hexian55** [comment] 2017-02-23 09:47
thanks,
I'll try it right away

**Comment by hexian55** [comment] 2017-02-24 01:40
hi 
@danielmitterdorfer     this is rally0.5.0 output
------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

|   Lap |                          Metric |            Operation |     Value |   Unit |
|------:|--------------------------------:|---------------------:|----------:|-------:|
|   All |                   Indexing time |                      |    32.811 |    min |
|   All |                      Merge time |                      |   7.46855 |    min |
|   All |                    Refresh time |                      |   1.26915 |    min |
|   All |                      Flush time |                      |  0.116817 |    min |
|   All |             Merge throttle time |                      |    0.6582 |    min |
|   All |                Median CPU usage |                      |   486.449 |      % |
|   All |              Total Young Gen GC |                      |    16.466 |      s |
|   All |                Total Old Gen GC |                      |     1.291 |      s |
|   All |                      Index size |                      |   2.72839 |     GB |
|   All |                 Totally written |                      |   14.9317 |     GB |
|   All |          Heap used for segments |                      |   14.3577 |     MB |
|   All |        Heap used for doc values |                      | 0.0934601 |     MB |
|   All |             Heap used for terms |                      |   12.9962 |     MB |
|   All |             Heap used for norms |                      | 0.0668335 |     MB |
|   All |            Heap used for points |                      |  0.578552 |     MB |
|   All |     Heap used for stored fields |                      |  0.622635 |     MB |
|   All |                   Segment count |                      |        86 |        |
|   All |                  Min Throughput |         index-append |           | docs/s |
|   All |               Median Throughput |         index-append |           | docs/s |
|   All |                  Max Throughput |         index-append |           | docs/s |
|   All |                  Min Throughput |          force-merge |  0.465802 |  ops/s |
|   All |               Median Throughput |          force-merge |  0.465802 |  ops/s |
|   All |                  Max Throughput |          force-merge |  0.465802 |  ops/s |
|   All |      100.0th percentile latency |          force-merge |   2146.82 |     ms |
|   All | 100.0th percentile service time |          force-merge |   2146.82 |     ms |
|   All |                  Min Throughput |          index-stats |    100.06 |  ops/s |
|   All |               Median Throughput |          index-stats |   100.086 |  ops/s |
|   All |                  Max Throughput |          index-stats |   100.165 |  ops/s |
|   All |       50.0th percentile latency |          index-stats |   1.78538 |     ms |
|   All |       90.0th percentile latency |          index-stats |   2.53858 |     ms |
|   All |       99.0th percentile latency |          index-stats |   6.18555 |     ms |
|   All |       99.9th percentile latency |          index-stats |   14.3972 |     ms |
|   All |      100.0th percentile latency |          index-stats |   20.8157 |     ms |
|   All |  50.0th percentile service time |          index-stats |   1.72622 |     ms |
|   All |  90.0th percentile service time |          index-stats |   2.46575 |     ms |
|   All |  99.0th percentile service time |          index-stats |   3.73141 |     ms |
|   All |  99.9th percentile service time |          index-stats |   14.0932 |     ms |
|   All | 100.0th percentile service time |          index-stats |   20.7566 |     ms |
|   All |                  Min Throughput |           node-stats |   99.8069 |  ops/s |
|   All |               Median Throughput |           node-stats |   100.129 |  ops/s |
|   All |                  Max Throughput |           node-stats |   100.754 |  ops/s |
|   All |       50.0th percentile latency |           node-stats |   1.65671 |     ms |
|   All |       90.0th percentile latency |           node-stats |   1.88139 |     ms |
|   All |       99.0th percentile latency |           node-stats |   4.53143 |     ms |
|   All |       99.9th percentile latency |           node-stats |   15.8558 |     ms |
|   All |      100.0th percentile latency |           node-stats |   19.6752 |     ms |
|   All |  50.0th percentile service time |           node-stats |   1.59718 |     ms |
|   All |  90.0th percentile service time |           node-stats |   1.82028 |     ms |
|   All |  99.0th percentile service time |           node-stats |   4.43389 |     ms |
|   All |  99.9th percentile service time |           node-stats |   6.76341 |     ms |
|   All | 100.0th percentile service time |           node-stats |   19.6159 |     ms |
|   All |                  Min Throughput |              default |   41.0168 |  ops/s |
|   All |               Median Throughput |              default |   41.3154 |  ops/s |
|   All |                  Max Throughput |              default |   41.4634 |  ops/s |
|   All |       50.0th percentile latency |              default |   4189.69 |     ms |
|   All |       90.0th percentile latency |              default |   5856.63 |     ms |
|   All |       99.0th percentile latency |              default |   6160.22 |     ms |
|   All |       99.9th percentile latency |              default |    6187.8 |     ms |
|   All |      100.0th percentile latency |              default |   6189.65 |     ms |
|   All |  50.0th percentile service time |              default |   22.7831 |     ms |
|   All |  90.0th percentile service time |              default |   27.6252 |     ms |
|   All |  99.0th percentile service time |              default |   37.8507 |     ms |
|   All |  99.9th percentile service time |              default |   41.6064 |     ms |
|   All | 100.0th percentile service time |              default |   42.7039 |     ms |
|   All |                  Min Throughput |                 term |   200.118 |  ops/s |
|   All |               Median Throughput |                 term |   200.164 |  ops/s |
|   All |                  Max Throughput |                 term |   200.273 |  ops/s |
|   All |       50.0th percentile latency |                 term |  0.905934 |     ms |
|   All |       90.0th percentile latency |                 term |   1.05642 |     ms |
|   All |       99.0th percentile latency |                 term |   1.50943 |     ms |
|   All |       99.9th percentile latency |                 term |   4.31841 |     ms |
|   All |      100.0th percentile latency |                 term |   8.41257 |     ms |
|   All |  50.0th percentile service time |                 term |  0.847061 |     ms |
|   All |  90.0th percentile service time |                 term |  0.997046 |     ms |
|   All |  99.0th percentile service time |                 term |   1.43895 |     ms |
|   All |  99.9th percentile service time |                 term |   2.78212 |     ms |
|   All | 100.0th percentile service time |                 term |    2.8597 |     ms |
|   All |                  Min Throughput |               phrase |   200.103 |  ops/s |
|   All |               Median Throughput |               phrase |   200.146 |  ops/s |
|   All |                  Max Throughput |               phrase |   200.246 |  ops/s |
|   All |       50.0th percentile latency |               phrase |   1.38629 |     ms |
|   All |       90.0th percentile latency |               phrase |   1.49302 |     ms |
|   All |       99.0th percentile latency |               phrase |     2.133 |     ms |
|   All |       99.9th percentile latency |               phrase |   6.41381 |     ms |
|   All |      100.0th percentile latency |               phrase |     8.168 |     ms |
|   All |  50.0th percentile service time |               phrase |   1.32675 |     ms |
|   All |  90.0th percentile service time |               phrase |   1.43358 |     ms |
|   All |  99.0th percentile service time |               phrase |   1.87686 |     ms |
|   All |  99.9th percentile service time |               phrase |   6.16181 |     ms |
|   All | 100.0th percentile service time |               phrase |    6.3527 |     ms |
|   All |                  Min Throughput | country_agg_uncached |   6.56864 |  ops/s |
|   All |               Median Throughput | country_agg_uncached |   6.57998 |  ops/s |
|   All |                  Max Throughput | country_agg_uncached |   6.60667 |  ops/s |
|   All |       50.0th percentile latency | country_agg_uncached |    132289 |     ms |
|   All |       90.0th percentile latency | country_agg_uncached |    185043 |     ms |
|   All |       99.0th percentile latency | country_agg_uncached |    196928 |     ms |
|   All |       99.9th percentile latency | country_agg_uncached |    198127 |     ms |
|   All |      100.0th percentile latency | country_agg_uncached |    198255 |     ms |
|   All |  50.0th percentile service time | country_agg_uncached |   147.791 |     ms |
|   All |  90.0th percentile service time | country_agg_uncached |   153.403 |     ms |
|   All |  99.0th percentile service time | country_agg_uncached |   231.311 |     ms |
|   All |  99.9th percentile service time | country_agg_uncached |   241.006 |     ms |
|   All | 100.0th percentile service time | country_agg_uncached |   253.528 |     ms |
|   All |                  Min Throughput |   country_agg_cached |   100.065 |  ops/s |
|   All |               Median Throughput |   country_agg_cached |   100.095 |  ops/s |
|   All |                  Max Throughput |   country_agg_cached |   100.181 |  ops/s |
|   All |       50.0th percentile latency |   country_agg_cached |  0.989484 |     ms |
|   All |       90.0th percentile latency |   country_agg_cached |   1.04417 |     ms |
|   All |       99.0th percentile latency |   country_agg_cached |   1.51803 |     ms |
|   All |       99.9th percentile latency |   country_agg_cached |   1.88119 |     ms |
|   All |      100.0th percentile latency |   country_agg_cached |   2.35046 |     ms |
|   All |  50.0th percentile service time |   country_agg_cached |  0.929739 |     ms |
|   All |  90.0th percentile service time |   country_agg_cached |  0.984646 |     ms |
|   All |  99.0th percentile service time |   country_agg_cached |   1.45287 |     ms |
|   All |  99.9th percentile service time |   country_agg_cached |   1.80662 |     ms |
|   All | 100.0th percentile service time |   country_agg_cached |   2.27092 |     ms |
|   All |                  Min Throughput |               scroll |   55.7498 |  ops/s |
|   All |               Median Throughput |               scroll |   56.1795 |  ops/s |
|   All |                  Max Throughput |               scroll |   56.2428 |  ops/s |
|   All |       50.0th percentile latency |               scroll |    424860 |     ms |
|   All |       90.0th percentile latency |               scroll |    595021 |     ms |
|   All |       99.0th percentile latency |               scroll |    633258 |     ms |
|   All |       99.9th percentile latency |               scroll |    637053 |     ms |
|   All |      100.0th percentile latency |               scroll |    637471 |     ms |
|   All |  50.0th percentile service time |               scroll |   443.367 |     ms |
|   All |  90.0th percentile service time |               scroll |   462.901 |     ms |
|   All |  99.0th percentile service time |               scroll |   475.367 |     ms |
|   All |  99.9th percentile service time |               scroll |   485.138 |     ms |
|   All | 100.0th percentile service time |               scroll |   485.212 |     ms |
|   All |                  Min Throughput |           expression |   3.96004 |  ops/s |
|   All |               Median Throughput |           expression |   3.96754 |  ops/s |
|   All |                  Max Throughput |           expression |   3.98053 |  ops/s |
|   All |       50.0th percentile latency |           expression |    201492 |     ms |
|   All |       90.0th percentile latency |           expression |    283417 |     ms |
|   All |       99.0th percentile latency |           expression |    301113 |     ms |
|   All |       99.9th percentile latency |           expression |    302887 |     ms |
|   All |      100.0th percentile latency |           expression |    303084 |     ms |
|   All |  50.0th percentile service time |           expression |    246.58 |     ms |
|   All |  90.0th percentile service time |           expression |   253.133 |     ms |
|   All |  99.0th percentile service time |           expression |   354.131 |     ms |
|   All |  99.9th percentile service time |           expression |   372.652 |     ms |
|   All | 100.0th percentile service time |           expression |   379.678 |     ms |
|   All |                  Min Throughput |      painless_static |   2.50931 |  ops/s |
|   All |               Median Throughput |      painless_static |   2.51899 |  ops/s |
|   All |                  Max Throughput |      painless_static |   2.53951 |  ops/s |
|   All |       50.0th percentile latency |      painless_static |    347682 |     ms |
|   All |       90.0th percentile latency |      painless_static |    486063 |     ms |
|   All |       99.0th percentile latency |      painless_static |    518068 |     ms |
|   All |       99.9th percentile latency |      painless_static |    520969 |     ms |
|   All |      100.0th percentile latency |      painless_static |    521300 |     ms |
|   All |  50.0th percentile service time |      painless_static |   365.834 |     ms |
|   All |  90.0th percentile service time |      painless_static |   497.791 |     ms |
|   All |  99.0th percentile service time |      painless_static |   664.236 |     ms |
|   All |  99.9th percentile service time |      painless_static |   693.875 |     ms |
|   All | 100.0th percentile service time |      painless_static |   711.225 |     ms |
|   All |                  Min Throughput |     painless_dynamic |    2.3758 |  ops/s |
|   All |               Median Throughput |     painless_dynamic |   2.39159 |  ops/s |
|   All |                  Max Throughput |     painless_dynamic |   2.39815 |  ops/s |
|   All |       50.0th percentile latency |     painless_dynamic |    368872 |     ms |
|   All |       90.0th percentile latency |     painless_dynamic |    514331 |     ms |
|   All |       99.0th percentile latency |     painless_dynamic |    547479 |     ms |
|   All |       99.9th percentile latency |     painless_dynamic |    550594 |     ms |
|   All |      100.0th percentile latency |     painless_dynamic |    550920 |     ms |
|   All |  50.0th percentile service time |     painless_dynamic |   385.994 |     ms |
|   All |  90.0th percentile service time |     painless_dynamic |   516.651 |     ms |
|   All |  99.0th percentile service time |     painless_dynamic |   686.609 |     ms |
|   All |  99.9th percentile service time |     painless_dynamic |   775.332 |     ms |
|   All | 100.0th percentile service time |     painless_dynamic |   801.522 |     ms |


but  some  indicators are output empty .    I need these indicators very much, Used to evaluate the amount of write per second

|   All |                  Min Throughput |         index-append |           | docs/s |
|   All |               Median Throughput |         index-append |           | docs/s |
|   All |                  Max Throughput |         index-append |           | docs/s |

**Comment by danielmitterdorfer** [comment] 2017-02-24 08:46
Hi @hexian55,

I am almost certain that you are experiencing indexing errors. Unfortunately, #234 is not yet ready but as you have an Elasticsearch metrics store (as I can see from your `~/.rally/rally.ini`) you can issue the following query against your metrics store to see all errors that have occurred:

```
GET /rally-2017/metrics/_search
{
  "query": {
    "bool": {
      "minimum_number_should_match": 1, 
      "must": [
        {
          "term": {
            "operation": {
              "value": "index-append"
            }
          }
        },
        {
          "term": {
            "name": {
              "value": "service_time"
            }
          }
        }
      ],
      "should": [
        {
          "term": {
            "meta.success": {
              "value": false
            }
          }
        },
        {
          "exists": {
            "field": "meta.error-description"
          }
        }
      ]
    }
  },
  "sort": [
    {
      "trial-timestamp": {
        "order": "desc"
      }
    }
  ]
}
```

You can also check the log files of the benchmarked Elasticsearch cluster in `~/.rally/benchmark/races/YOUR_RACETIMESTAMP_HERE/esrally_test/logs/server`. `YOUR_RACETIMESTAMP_HERE` depends on when you started a benchmark. Just do an `ls -l` in `~/.rally/benchmark/races` and find the most recent timestamp.

**Comment by hexian55** [comment] 2017-02-24 09:03
hi  @danielmitterdorfer 
I not find any error

cat rally-benchmark.log

[2017-02-24T15:49:00,185][INFO ][o.e.n.Node               ] [rally-node0] initializing ...
[2017-02-24T15:49:00,243][INFO ][o.e.e.NodeEnvironment    ] [rally-node0] using [1] data paths, mounts [[/home (/dev/mapper/vg_root-lv_home)]], net usable_space [2.3tb], net total_space [2.5tb], spins? [possibly], types [ext4]
[2017-02-24T15:49:00,243][INFO ][o.e.e.NodeEnvironment    ] [rally-node0] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-02-24T15:49:00,244][INFO ][o.e.n.Node               ] [rally-node0] node name [rally-node0], node ID [9dpNs8bKR66Lv2s0iq3xYw]
[2017-02-24T15:49:00,246][INFO ][o.e.n.Node               ] [rally-node0] version[5.2.0], pid[193293], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Linux/3.10.0-123.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_111/25.111-b14]
[2017-02-24T15:49:00,941][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [aggs-matrix-stats]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [ingest-common]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [lang-expression]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [lang-groovy]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [lang-mustache]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [lang-painless]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [percolator]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [reindex]
[2017-02-24T15:49:00,942][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [transport-netty3]
[2017-02-24T15:49:00,943][INFO ][o.e.p.PluginsService     ] [rally-node0] loaded module [transport-netty4]
[2017-02-24T15:49:00,943][INFO ][o.e.p.PluginsService     ] [rally-node0] no plugins loaded
[2017-02-24T15:49:02,638][INFO ][o.e.n.Node               ] [rally-node0] initialized
[2017-02-24T15:49:02,639][INFO ][o.e.n.Node               ] [rally-node0] starting ...
[2017-02-24T15:49:02,818][INFO ][o.e.t.TransportService   ] [rally-node0] publish_address {127.0.0.1:39300}, bound_addresses {127.0.0.1:39300}
[2017-02-24T15:49:05,864][INFO ][o.e.c.s.ClusterService   ] [rally-node0] new_master {rally-node0}{9dpNs8bKR66Lv2s0iq3xYw}{k8X7jxqiSjiWQ60eaDHfDg}{127.0.0.1}{127.0.0.1:39300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-02-24T15:49:05,880][INFO ][o.e.h.HttpServer         ] [rally-node0] publish_address {127.0.0.1:39200}, bound_addresses {127.0.0.1:39200}
[2017-02-24T15:49:05,880][INFO ][o.e.n.Node               ] [rally-node0] started
[2017-02-24T15:49:05,885][INFO ][o.e.g.GatewayService     ] [rally-node0] recovered [0] indices into cluster_state
[2017-02-24T15:49:06,176][INFO ][o.e.c.m.MetaDataCreateIndexService] [rally-node0] [geonames] creating index, cause [api], templates [], shards [5]/[0], mappings []
[2017-02-24T15:49:06,337][INFO ][o.e.c.r.a.AllocationService] [rally-node0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[geonames][4]] ...]).
[2017-02-24T15:49:06,392][INFO ][o.e.c.m.MetaDataMappingService] [rally-node0] [geonames/YiZhZmHKQi6qBpDree6_Bw] create_mapping [type]
[2017-02-24T16:33:50,092][INFO ][o.e.n.Node               ] [rally-node0] stopping ...
[2017-02-24T16:33:50,142][INFO ][o.e.n.Node               ] [rally-node0] stopped
[2017-02-24T16:33:50,142][INFO ][o.e.n.Node               ] [rally-node0] closing ...
[2017-02-24T16:33:50,157][INFO ][o.e.n.Node               ] [rally-node0] closed

**Comment by danielmitterdorfer** [comment] 2017-02-24 10:22
Ok, the logs look fine indeed and the cluster also did not stop prematurely due to an error. Now it could still be possible that you get bulk indexing errors. Did you also run the query against your metrics store that I've provided above? Did it produce any results?

**Comment by hexian55** [comment] 2017-02-27 01:32
I tried geopoint,it's ok
esrally --distribution-version=5.2.0 --track=geopoint --challenge=append-fast-with-conflicts

thank you very match.
------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

|   Lap |                          Metric |    Operation |     Value |   Unit |
|------:|--------------------------------:|-------------:|----------:|-------:|
|   All |                   Indexing time |              |   108.633 |    min |
|   All |                      Merge time |              |   16.5252 |    min |
|   All |                    Refresh time |              |   1.05188 |    min |
|   All |             Merge throttle time |              |   0.51235 |    min |
|   All |                Median CPU usage |              |   1272.05 |      % |
|   All |              Total Young Gen GC |              |    54.202 |      s |
|   All |                Total Old Gen GC |              |     3.296 |      s |
|   All |                      Index size |              |   2.52004 |     GB |
|   All |                 Totally written |              |   24.5554 |     GB |
|   All |          Heap used for segments |              |   11.4174 |     MB |
|   All |        Heap used for doc values |              | 0.0129738 |     MB |
|   All |             Heap used for terms |              |   10.2806 |     MB |
|   All |            Heap used for points |              |  0.404301 |     MB |
|   All |     Heap used for stored fields |              |  0.719505 |     MB |
|   All |                   Segment count |              |       139 |        |
|   All |                  Min Throughput | index-update |    112839 | docs/s |
|   All |               Median Throughput | index-update |    120876 | docs/s |
|   All |                  Max Throughput | index-update |    124262 | docs/s |
|   All |       50.0th percentile latency | index-update |   211.908 |     ms |
|   All |       90.0th percentile latency | index-update |   564.618 |     ms |
|   All |       99.0th percentile latency | index-update |   1185.83 |     ms |
|   All |       99.9th percentile latency | index-update |   1651.13 |     ms |
|   All |      100.0th percentile latency | index-update |   1898.26 |     ms |
|   All |  50.0th percentile service time | index-update |   211.951 |     ms |
|   All |  90.0th percentile service time | index-update |   564.639 |     ms |
|   All |  99.0th percentile service time | index-update |   1185.83 |     ms |
|   All |  99.9th percentile service time | index-update |   1651.13 |     ms |
|   All | 100.0th percentile service time | index-update |   1898.26 |     ms |
|   All |                  Min Throughput |  force-merge |  0.200015 |  ops/s |
|   All |               Median Throughput |  force-merge |  0.200015 |  ops/s |
|   All |                  Max Throughput |  force-merge |  0.200015 |  ops/s |
|   All |      100.0th percentile latency |  force-merge |   4999.62 |     ms |
|   All | 100.0th percentile service time |  force-merge |   4999.62 |     ms |

**Comment by danielmitterdorfer** [comment] 2017-02-27 06:18
You're welcome. I'm closing it then as it is already fixed.

**Closed by danielmitterdorfer** 2017-02-27 06:18 UTC
Labels: :Reporting, bug
