### ISSUE TITLE
Error in report_search_latency when use benchmark-only

### ISSUE THREAD

**Issue by adolia** [elastic/rally#124] opened 2016-07-27 11:15 UTC
An error occurs when try to display the report:
------------------------------------------------------
    _______             __   _____                    
   / ____(_)___  ____ _/ /  / ___/_________  ________ 
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/ 
------------------------------------------------------
Traceback (most recent call last):
  File "/bin/esrally", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/esrally/rally.py", line 276, in main
    success = dispatch_sub_command(cfg, sub_command)
  File "/usr/lib/python3.4/site-packages/esrally/rally.py", line 228, in dispatch_sub_command
    return race_control.start(sub_command)
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 317, in start
    raise e
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 297, in start
    pipeline()
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 94, in __call__
    step()
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 25, in __call__
    self.command(self.ctx)
  File "/usr/lib/python3.4/site-packages/esrally/racecontrol.py", line 271, in <lambda>
    PipelineStep("report", ctx, lambda ctx: ctx.reporter.report(ctx.track)),
  File "/usr/lib/python3.4/site-packages/esrally/reporter.py", line 158, in report
    metrics_table += self.report_search_latency(stats)
  File "/usr/lib/python3.4/site-packages/esrally/reporter.py", line 192, in report_search_latency
    for percentile, value in latency.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by danielmitterdorfer** [comment] 2016-07-27 14:48
Can you please give a little bit more detail so I can reproduce this? It seems to be related to #110 (which is already fixed on master).

Specifically: Can you please share `~/.rally/rally.ini`? and the output of `esrally --version`?

**Comment by adolia** [comment] 2016-07-27 14:52
$ esrally --version
esrally 0.3.0

~/.rally/rally.ini
[meta]
config.version = 5

[system]
root.dir = /root/.rally/benchmarks
log.root.dir = logs
env.name = celare

[provisioning]
local.install.dir = install

[runtime]
java8.home = /usr/local/bin

[benchmarks]
local.dataset.cache = ${system:root.dir}/data

[reporting]
datastore.type = elasticsearch
datastore.host = localhost
datastore.port = 9200
datastore.secure = False
datastore.user =
datastore.password =

[tracks]
default.url = https://github.com/elastic/rally-tracks

**Comment by danielmitterdorfer** [comment] 2016-07-27 15:13
Thanks for sharing the info. This is a duplicate of #110 and is already fixed on master hence I am closing it. I see if I can get a bugfix release out so you can have the fix before 0.4.0 is out.

**Closed by danielmitterdorfer** 2016-07-27 15:13 UTC
Labels: duplicate

**Comment by danielmitterdorfer** [comment] 2016-07-27 17:28
@adolia I have just release Rally 0.3.1 (see the [announcement on Discuss](https://discuss.elastic.co/t/rally-0-3-1-released/56550)) so the problem should be gone now after the update. /cc: @eugenemiretsky (same as issue #110 that you've reported).

**Comment by adolia** [comment] 2016-07-27 17:31
Thanks a lot!
