### ISSUE TITLE
esrally: error: --target-hosts and --client-options must define the same keys for multi cluster setups.

### ISSUE THREAD

**Issue by sangkyunkim89** [elastic/rally#1558] opened 2022-08-03 14:12 UTC
**Rally version** elastic/rally latest version 
![스크린샷 2022-08-03 오후 11 08 48](https://user-images.githubusercontent.com/65607130/182629381-92a2bfcb-df31-4edb-a531-50f0a37639b2.png)

The command is as shown above. Because the destination elasticsearch uses xpack, I use client-options to prevent a security exception.

```
    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[ERROR] Cannot race. 2.

Getting further help:
*********************
* Check the log files in /rally/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/2.6.0/.
usage: esrally [-h] [--version]
               {race,list,info,create-track,generate,compare,download,install,start,stop}
               ...
esrally: error: --target-hosts and --client-options must define the same keys for multi cluster setups.
* Ask a question on the forum at https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally.
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /rally/.rally/logs.
```

Even after looking at the official documentation, I can't quite understand... The official documentation only says to use it as above. What should I do?

target-hosts is only one
im use elasticsearch eck!

**Comment by pquentin** [comment] 2022-08-09 13:00
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

However, I think the issue is that your `--target-hosts` parameter is malformed, and parses to a JSON dictionary somehow? Which means Rally thinks you have multiple clusters. It's not easy to tell as you've hidden the important part. :)

**Closed by pquentin** 2022-08-09 13:00 UTC

**Comment by sangkyunkim89** [comment] 2022-08-10 01:24
@pquentin 
hi thank you so much for replying
However, the target host has only one cluster, not multiple clusters.

**Comment by b-deam** [comment] 2022-08-10 01:35
Hi @sangkyunkim89 , sorry about the dead link. You can post the [question here](https://discuss.elastic.co/tag/rally) and tag it with `rally` so that we can help out. As @pquentin mentioned, please be sure to include the full invocation so we can help out.
