### ISSUE TITLE
trouble reporting benchmark results

### ISSUE THREAD

**Issue by rmuir** [elastic/rally#93] opened 2016-05-03 22:01 UTC
I followed the guidelines here (http://esrally.readthedocs.io/en/latest/developing.html#installation-instructions-for-development) because I wanted to see if i could benchmark scripting engines in ES master.

I got up and running, but at the end I hit this:
```
rmuir@beast:~/workspace/rally$ esrally race

Writing additional logs to /data/rally/races/2016-05-03-21-29-51/scripts/logs/rally_out.log

    ____        ____     
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ / 
/_/ |_|\__,_/_/_/\__, /  
                /____/   
Preparing for race (might take a few moments) ...
  Building from sources ...
Racing on track 'geonames' with setup 'defaults'
  Benchmarking indexing at 23543.6 docs/s                            [100% done]
  Benchmarking stats (warmup iteration 100/100)                      [100% done]
  Benchmarking stats (iteration 100/100)                             [100% done]
  Benchmarking search (warmup iteration 1000/1000)                   [100% done]
  Benchmarking search (iteration 1000/1000)                          [100% done]
------------------------------------------------------
    _______             __   _____                    
   / ____(_)___  ____ _/ /  / ___/_________  ________ 
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/ 
------------------------------------------------------
Indexing Results (Throughput):
  Could not determine indexing throughput

Total times:
Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 9, in <module>
    load_entry_point('esrally==0.2.1.dev0', 'console_scripts', 'esrally')()
  File "/home/rmuir/workspace/rally/esrally/rally.py", line 238, in main
    success = race_control.start(subcommand)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 260, in start
    pipeline.run(t)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 88, in run
    step.run(track)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 27, in run
    self.command(self.ctx, track)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 198, in <lambda>
    PipelineStep("report", ctx, lambda ctx, track: ctx.reporter.report(track)),
  File "/home/rmuir/workspace/rally/esrally/reporter.py", line 38, in report
    self.report_total_times(store)
  File "/home/rmuir/workspace/rally/esrally/reporter.py", line 88, in report_total_times
    print("  Indexing time      : %.1f min" % convert.ms_to_minutes(store.get_one("indexing_total_time")))
  File "/home/rmuir/workspace/rally/esrally/utils/convert.py", line 22, in ms_to_minutes
    return ms / 1000.0 / 60.0
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 9, in <module>
    load_entry_point('esrally==0.2.1.dev0', 'console_scripts', 'esrally')()
  File "/home/rmuir/workspace/rally/esrally/rally.py", line 238, in main
    success = race_control.start(subcommand)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 260, in start
    pipeline.run(t)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 88, in run
    step.run(track)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 27, in run
    self.command(self.ctx, track)
  File "/home/rmuir/workspace/rally/esrally/racecontrol.py", line 198, in <lambda>
    PipelineStep("report", ctx, lambda ctx, track: ctx.reporter.report(track)),
  File "/home/rmuir/workspace/rally/esrally/reporter.py", line 38, in report
    self.report_total_times(store)
  File "/home/rmuir/workspace/rally/esrally/reporter.py", line 88, in report_total_times
    print("  Indexing time      : %.1f min" % convert.ms_to_minutes(store.get_one("indexing_total_time")))
  File "/home/rmuir/workspace/rally/esrally/utils/convert.py", line 22, in ms_to_minutes
    return ms / 1000.0 / 60.0
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by jasontedor** [comment] 2016-05-03 22:25
I ran into this too, I assumed it was just my machine because I ran into trouble getting it installed on my Fedora workstation (lots of missing packages that were not obvious what needed to be installed), and I installed it into a virtual environment. Now it's clear it is not due to that.

**Comment by danielmitterdorfer** [comment] 2016-05-04 08:12
I check whether I can reproduce this on a (virtual) Fedora box.

**Comment by danielmitterdorfer** [comment] 2016-05-04 09:23
I created a Fedora 23 box just with Java. Here is my `Vagrantfile`.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "elastic/fedora-23-x86_64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
  end

  config.vm.provision "shell", inline: <<-SHELL
    wget -nv --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-x64.rpm"
    rpm -Uvh jdk-8u91-linux-x64.rpm
  SHELL
end
```

After that I had to install a few packages:

```
sudo dnf install gcc python3-devel redhat-rpm-config
```

This is because I use the library `psutil` to gather CPU usage and other system metrics. This library builds a native extension. After that I followed the [installation instructions for development](http://esrally.readthedocs.io/en/latest/developing.html) (note that I have already updated them now so they also list all prerequisites explicitly) except that I installed Rally with `sudo`, i.e. I issued `sudo python3 setup.py develop`.

Then I started the Elasticsearch metrics store, configured Rally and ran the tiny track (`esrally --track=tiny`) which ran fine.

The trace that Robert has posted indicates that Rally could not store data in the data store at all. @rmuir: Could you please upload `/data/rally/races/2016-05-03-21-29-51/scripts/logs/rally_out.log`? Hopefully this reveals something interesting.

**Comment by danielmitterdorfer** [comment] 2016-05-04 12:47
@rmuir we got it sorted out. The root cause was that no records were found due to a problem with the mapping in the metrics store. Can you please pull the latest version of Rally, wipe the indices in the metrics store and retry?

**Comment by rmuir** [comment] 2016-05-04 13:28
Thanks!! I will try again. Just a bit under the weather causing me to be slow to respond.

**Comment by danielmitterdorfer** [comment] 2016-05-04 13:56
@rmuir no worries. Please just ping if this still causes trouble for you! I am glad to help.

**Comment by danielmitterdorfer** [comment] 2016-05-10 12:30
@rmuir Does this work for you now or is do I have to fix something here?

**Comment by danielmitterdorfer** [comment] 2016-05-23 12:05
I am closing this one in favor of #102. With the simpler setup (which does not require a dedicated metrics store anymore) this problem should not happen anymore.

**Closed** 2016-06-06 08:35 UTC
Labels: bug
