### ISSUE TITLE
Chart Generator: Support multiple indexing tasks in the same challenge

### ISSUE THREAD

**Issue by inqueue** [elastic/rally#1519] opened 2022-06-15 18:54 UTC
The Rally chart generator does not appear to support parallel tasks, as defined in the [dense vector track](https://github.com/elastic/rally-tracks/blob/688d04ba3f1e3748307ab59fcc1586951ec290f4/dense_vector/challenges/default.json#L56). The following command does not produce charts for operations in parallel tasks:

```sh
$ esrally generate charts --configuration-name=nightly --chart-spec-path=~/dev/src/night-rally/night_rally/resources/race-configs-group-3.json --chart-type=time-series --output-path=~/tmp/nightly-dv-charts.ndjson

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Loading track data...
[INFO] Generating charts...
[INFO] Found [bulk-index] of type [raw-bulk] in [logging-indexing], adding it to indexing dashboard.

[INFO] Found [bulk-index-initial-load] of type [raw-bulk] in [security-indexing-querying], adding it to indexing dashboard.

[INFO] Found [bulk-index] of type [raw-bulk] in [security-indexing], adding it to indexing dashboard.
```

@pquentin @mayya-sharipova this is required for dense vector track chart generation.

**Comment by pquentin** [comment] 2022-06-16 11:29
The issue isn't about parallel tasks, we support them just fine. What's going on is that we have two indexing tasks in the same challenge, which isn't supported (the query chart is just fine). So we do have two indexing tasks, but they're both named "add-4g-1node". We can this clearly when looking at the generated charts with a 90 days interval:

![image](https://user-images.githubusercontent.com/42327/174059919-8df733ed-00a9-48e2-bf00-3b38dd988f11.png)

There are two ways to get out of here:

* Modify the track to include two challenges, each one of them performing a single index (one parallel, one not)
* We modify all the indexing charts to add the name of the task in the legend, eg we would have "add-4g-1node-index-append" and "add-4g-1node-index-update-concurrent-with-searches" which would be verbose but explicit.

**Comment by pquentin** [comment] 2022-06-17 12:14
We actually have the same issue for the many-shards benchmark, so we'll support this eventually but for now we'll manually edit the labels before uploading.

**Comment by ebadyano** [comment] 2022-09-15 19:11
@pquentin should we close this one now, as we agreed to stop supporting chart generator?

**Comment by pquentin** [comment] 2022-09-15 20:07
Yes, thanks.

**Closed by pquentin** 2022-09-15 20:07 UTC
Labels: enhancement, :internal
